language: ruby
matrix:
  exclude:
    - rvm: jruby-18mode
      gemfile: Gemfile
    - rvm: rbx-18mode
      gemfile: Gemfile
    - rvm: 1.9.2
      gemfile: Gemfile
    - rvm: ree
      gemfile: Gemfile
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-2.1.x
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-2.1.x
    - rvm: rbx-19mode
      gemfile: gemfiles/Gemfile.rails-2.1.x
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.rails-2.1.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-2.1.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-2.3.x
  allow_failures:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.rails-2.1.x
    - rvm: ree
      gemfile: gemfiles/Gemfile.rails-2.1.x
    - rvm: rbx-18mode
      gemfile: gemfiles/Gemfile.rails-2.1.x
    - rvm: jruby-18mode
      gemfile: gemfiles/Gemfile.rails-2.1.x

rvm: 
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 1.8.7
  - ree
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-2.1.x
  - gemfiles/Gemfile.rails-2.3.x
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-3.2.x